### ISSUE TITLE
Probability Sampler for Tracer

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#162] opened 2020-08-12 15:18 UTC
At the time of working through #14 , the probablity sampler wasn't hashed out.  There is now more information on this probability sampler: 

https://github.com/open-telemetry/opentelemetry-specification/blob/bc272ab52869df2145065d55300d721ff008e34b/specification/trace/sdk.md#probability

Success criteria: Implement the probability sampler for the tracer.

**Comment by bobstrecansky** [comment] 2020-08-12 15:18
@zsistla is going to be working on this.

**Comment by bobstrecansky** [comment] 2020-09-23 12:11
@shovnik opened a PR for this work:
https://github.com/open-telemetry/opentelemetry-php/pull/182

**Comment by shovnik** [comment] 2020-09-23 16:44
Isn't this issue a duplicate of issue #86? Should one of them be closed as a duplicate? I did not mean to steal @zsistla 's issue by making this pr.

**Comment by zsistla** [comment] 2020-09-23 17:09
Hi @shovnik,

No worries.
Hopefully with the great boards(
Tracing: https://github.com/open-telemetry/opentelemetry-php/projects/1
Metrics: https://github.com/open-telemetry/opentelemetry-php/projects/2) @bobstrecansky just put together, duplications like this will be reduced.

**Closed** 2020-10-10 20:31 UTC
