### ISSUE TITLE
parse error with otlp/json response from honeycomb.io

### ISSUE THREAD

**Issue by adamlyka** [open-telemetry/opentelemetry-php#1100] opened 2023-08-14 06:38 UTC
Currently using the following package versions on PHP 8.0.2:
"open-telemetry/exporter-otlp": "1.0.0beta12@beta",
"open-telemetry/opentelemetry-auto-laravel": "0.0.9",
"open-telemetry/sdk": "1.0.0beta15",

**Steps to reproduce**
Have setup the laravel otel package and currently using auto intstrumentation with the following config:
putenv('OTEL_SERVICE_NAME=myService');
putenv('OTEL_PHP_AUTOLOAD_ENABLED=true');
putenv('OTEL_METRICS_EXPORTER=none');
putenv('OTEL_LOGS_EXPORTER=none');
putenv('OTEL_TRACES_EXPORTER=otlp');
putenv('OTEL_EXPORTER_OTLP_PROTOCOL=http/json');
putenv('OTEL_PROPAGATORS=baggage,tracecontext');

**What is the expected behavior?**
When exporting traces, there should be no errors thrown when traces are sent via otlp and there are large delays when sending data (even when making only 3 transactions)

**What is the actual behavior?**
Following errors are thrown per trace sent:
``` WARN  PHP Fatal error: Uncaught ErrorException: Unhandled export error: Export failure: Error occurred during parsing: Cannot decode json string: .  

   WARN  #0 vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(795): Google\Protobuf\Internal\Message->parseFromJsonStream().  

   WARN  #1 vendor/open-telemetry/exporter-otlp/ProtobufSerializer.php(108): Google\Protobuf\Internal\Message->mergeFromJsonString().  

   WARN  #2 vendor/open-telemetry/exporter-otlp/SpanExporter.php(48): OpenTelemetry\Contrib\Otlp\ProtobufSerializer->hydrate().  

   WARN  #3 vendor/open-telemetry/sdk/Common/Future/CompletedFuture.php(38): OpenTelemetry\Contrib\Otlp\SpanExporter->OpenTelemetry\Contrib\Otlp\{closure}().  

   WARN  #4 vendor/open-telemetry/exporter-otlp/SpanExporter.php(64): OpenTelemetry\SDK\Common\Future\CompletedFuture->map().  

   WARN  #5 vendor/open-telemetry/sdk/Trace/SpanProcessor/BatchSpanProcessor.php(255): OpenTelemetry\Contrib\Otlp\SpanExporter->export().  

   WARN  #6 vendor/open-telemetry/sdk/Trace/SpanProcessor/BatchSpanProcessor.php(198): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor->flush().  

   WARN  #7 vendor/open-telemetry/sdk/Trace/TracerSharedState.php(98): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor->shutdown().  

   WARN  #8 vendor/open-telemetry/sdk/Trace/TracerProvider.php(92): OpenTelemetry\SDK\Trace\TracerSharedState->shutdown().  

   WARN  #9 vendor/open-telemetry/sdk/Common/Util/functions.php(36): OpenTelemetry\SDK\Trace\TracerProvider->shutdown().  

   WARN  #10 [internal function]: OpenTelemetry\SDK\Trace\TracerProvider->OpenTelemetry\SDK\Common\Util\{closure}().  

   WARN  #11 vendor/open-telemetry/sdk/Common/Util/functions.php(50): Closure->call().  

   WARN  #12 vendor/open-telemetry/sdk/Common/Util/ShutdownHandler.php(76): OpenTelemetry\SDK\Common\Util\{closure}().  

   WARN  #13 [internal function]: OpenTelemetry\SDK\Common\Util\ShutdownHandler::OpenTelemetry\SDK\Common\Util\{closure}().  

   WARN  #14 {main}.  

   WARN  #0 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError().  

   WARN  #1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}().  

   WARN  #2 vendor/open-telemetry/api/Behavior/LogsMessagesTrait.php(46): trigger_error().  

   WARN  #3 vendor/open-telemetry/api/Behavior/LogsMessagesTrait.php(72): OpenTelemetry\Contrib\Otlp\SpanExporter::doLog().  

   WARN  #4 vendor/open-telemetry/exporter-otlp/SpanExporter.php(66): OpenTelemetry\Contrib\Otlp\SpanExporter::logError().  

   WARN  #5 vendor/open-telemetry/sdk/Common/Future/ErrorFuture.php(35): OpenTelemetry\Contrib\Otlp\SpanExporter::OpenTelemetry\Contrib\Otlp\{closure}().  

   WARN  #6 vendor/open-telemetry/exporter-otlp/SpanExporter.php(69): OpenTelemetry\SDK\Common\Future\ErrorFuture->catch().  

   WARN  #7 vendor/open-telemetry/sdk/Trace/SpanProcessor/BatchSpanProcessor.php(255): OpenTelemetry\Contrib\Otlp\SpanExporter->export().  

   WARN  #8 vendor/open-telemetry/sdk/Trace/SpanProcessor/BatchSpanProcessor.php(198): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor->flush().  

   WARN  #9 vendor/open-telemetry/sdk/Trace/TracerSharedState.php(98): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor->shutdown().  

   WARN  #10 vendor/open-telemetry/sdk/Trace/TracerProvider.php(92): OpenTelemetry\SDK\Trace\TracerSharedState->shutdown().  

   WARN  #11 vendor/open-telemetry/sdk/Common/Util/functions.php(36): OpenTelemetry\SDK\Trace\TracerProvider->shutdown().  

   WARN  #12 [internal function]: OpenTelemetry\SDK\Trace\TracerProvider->OpenTelemetry\SDK\Common\Util\{closure}().  

   WARN  #13 vendor/open-telemetry/sdk/Common/Util/functions.php(50): Closure->call().  

   WARN  #14 vendor/open-telemetry/sdk/Common/Util/ShutdownHandler.php(76): OpenTelemetry\SDK\Common\Util\{closure}().  

   WARN  #15 [internal function]: OpenTelemetry\SDK\Common\Util\ShutdownHandler::OpenTelemetry\SDK\Common\Util\{closure}().  

   WARN  #16 {main} in vendor/open-telemetry/api/Behavior/LogsMessagesTrait.php:46.  

   WARN  Stack trace:  

   WARN  #0 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError().  

   WARN  #1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}().  

   WARN  #2 vendor/open-telemetry/api/Behavior/LogsMessagesTrait.php(46): trigger_error().  

   WARN  #3 vendor/open-telemetry/api/Behavior/LogsMessagesTrait.php(72): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor::doLog().  

   WARN  #4 vendor/open-telemetry/sdk/Trace/SpanProcessor/BatchSpanProcessor.php(257): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor::logError().  

   WARN  #5 vendor/open-telemetry/sdk/Trace/SpanProcessor/BatchSpanProcessor.php(198): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor->flush().  

   WARN  #6 vendor/open-telemetry/sdk/Trace/TracerSharedState.php(98): OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor->shutdown().  

   WARN  #7 vendor/open-telemetry/sdk/Trace/TracerProvider.php(92): OpenTelemetry\SDK\Trace\TracerSharedState->shutdown().  

   WARN  #8 vendor/open-telemetry/sdk/Common/Util/functions.php(36): OpenTelemetry\SDK\Trace\TracerProvider->shutdown().  

   WARN  #9 [internal function]: OpenTelemetry\SDK\Trace\TracerProvider->OpenTelemetry\SDK\Common\Util\{closure}().  

   WARN  #10 vendor/open-telemetry/sdk/Common/Util/functions.php(50): Closure->call().  

   WARN  #11 vendor/open-telemetry/sdk/Common/Util/ShutdownHandler.php(76): OpenTelemetry\SDK\Common\Util\{closure}().  

   WARN  #12 [internal function]: OpenTelemetry\SDK\Common\Util\ShutdownHandler::OpenTelemetry\SDK\Common\Util\{closure}().  

   WARN  #13 {main}.  

   WARN  thrown in vendor/open-telemetry/api/Behavior/LogsMessagesTrait.php on line 46.  

  2023-08-14 06:25:43 ................................................... ~ 2s
```

**Additional context**
This is occurring when I export directly to the otlp endpoint from my laravel app
When using a collector, there are no errors thrown in the collector
In both scenarios, traces are sent to the 3rd party endpoint, just concerned at the errors

**Comment by brettmc** [comment] 2023-08-14 06:49
What that looks like, is that you received an invalid JSON response from the service you send traces to. It's not clear which service you are sending the traces to, but we've had one previous report that I can recall where a cloud-based service was sending back the response in the wrong format (eg send protobuf, receive json response, or similar).
To debug this further, can you please try to get more logging: https://github.com/open-telemetry/opentelemetry-php/blob/main/examples/traces/troubleshooting/setting_up_logging.php
If nothing interesting is shown there, can you try to capture the response (body + headers) when exporting?

**Comment by brettmc** [comment] 2023-08-14 07:14
> there are large delays when sending data

We don't (yet) support async sending of telemetry data, and it sounds like your issue is round-trip time to a cloud-based service. Our current recommendation is to use the otel collector as an agent: https://opentelemetry.io/docs/instrumentation/php/exporters/#minimizing-export-delays

**Comment by adamlyka** [comment] 2023-08-15 02:21
Looking at the response it just seems to be an empty string which is why it seems to be failing. For reference, I am exporting to Honeycomb.io

**Comment by brettmc** [comment] 2023-08-15 02:50
That sounds like the culprit. I just expanded our [testcase](https://github.com/open-telemetry/opentelemetry-php/blob/main/tests/Unit/Contrib/Otlp/ProtobufSerializerTest.php) locally to check both an empty string and `""`, and it choked on both. The latter should be valid.

Do you have a way to log tickets with honeycomb.io to verify with them that their response is ok? It wasn't empty because of a non-200 HTTP response, was it?
The relevant part of the spec is https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#otlphttp-response but it only says that the response should be JSON if the request was. I think it's implied that it would be valid JSON, which an empty string isn't, but I can ask about that in the spec SIG.

**Comment by adamlyka** [comment] 2023-08-15 04:46
I've just sent a message to their slack channels and will report back once I get a response

**Comment by brettmc** [comment] 2023-08-22 23:44
Hi @adamlyka any news back from the vendor?
I'd like to squash this bug, so if they're not responding I'd be willing to punt on a fix. We currently check for a null response, but I think we could expand that include single or double quoted empty strings. Are you able to get a var_dump of the exact response body and headers you get back?

**Comment by adamlyka** [comment] 2023-08-24 00:54
@brettmc I have contacted them and it is currently being looked at to reproduce and put together a fix. Will update here on any progress

**Comment by brettmc** [comment] 2024-02-06 23:02
I think we can close this - it sounds like the issue is on the vendor side. Please re-open if further work required on our side.

**Closed by brettmc** 2024-02-06 23:02 UTC
Labels: bug
