### ISSUE TITLE
Single function/common file manual php instrumentation

### ISSUE THREAD

**Issue by gajavallisantosh** [open-telemetry/opentelemetry-php#1119] opened 2023-09-30 22:30 UTC
Hello guys,

We have php 7.4 web application and it's a huge one. We would like to instrument it using open telemetry. The only option We see is manual instrumentation. Auto instrumentation is supported only on php 8.0+.

So, do we need to write code on every php file to complete instrument our web application or do we have some common functions/common library that can work all php pages. If so, please provide me a working example.

I was able to get traces and logs by adding dependencies in compose file but I had to write tracerprovider and monolog related code in php file....for a small example this is fine...how do we need to do it for a large Enterprise application. Please suggest/advice

**Comment by brettmc** [comment] 2023-10-01 03:44
Closing as duplicate of https://github.com/open-telemetry/opentelemetry-php-instrumentation/issues/91

**Closed by brettmc** 2023-10-01 03:44 UTC
Labels: bug

**Comment by Iv4nS** [comment] 2023-12-07 14:13
No idea what the solution of this is now... link shows 404.

**Comment by brettmc** [comment] 2023-12-08 01:02
We just closed issues over in that repo so that they could be centrally managed here. The "solution" over in that issue was:

> Hello @gajavallisantosh
The auto-instrumentation extension relies on features that were introduced in PHP 8.0, and it will never be able to work with 7.4.
If upgrading to PHP8+ is not an option for you, then you will have to use manual instrumentation. Unfortunately, yes that means dropping manual instrumentation code all throughout your application.
The only other option I can think of is if your application has events, then you could at least separate the manual instrumentation into event-based functions.
You could also try out https://github.com/plunkettscott/laravel-otel or https://packagist.org/packages/open-telemetry/symfony-sdk-bundle if your application is based on Laravel or Symfony. I haven't used them, but they do not require PHP8.

**Comment by gajavallisantosh** [comment] 2024-02-07 19:59
Hi, Thanks a lot for your time and patience. We were able to successfully instrument a roll dice application on redhatOS along with trace to logs correlation.
