### ISSUE TITLE
Implement support for Trace Semantic Conventions

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-php#297] opened 2021-03-31 16:42 UTC
We have not yet implemented anything for Trace Semantic Conventions, we need to do so.

See [Trace Semantic Conventions in the spec](https://github.com/open-telemetry/opentelemetry-specification/tree/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/semantic_conventions#trace-semantic-conventions)

**Question: do we need to define constants for all of the attributes in the spec?**

**Comment by bobstrecansky** [comment] 2021-08-05 14:24
This is a duplicate of https://github.com/open-telemetry/opentelemetry-php/issues/376

**Closed by bobstrecansky** 2021-08-05 14:24 UTC
Labels: release:required-for-ga
